FROM ibmcom/powerai:1.6.2-base-ubuntu18.04-py37
RUN /opt/anaconda/bin/conda install -n wmlce -y pandas joblib py-xgboost-cpu scikit-learn tornado libxgboost-base boost protobuf grpcio Flask cffi 
RUN sudo apt-get update && sudo apt-get install -y build-essential gcc libssl-dev libffi-dev
RUN eval "$(/opt/anaconda/bin/conda shell.bash hook |sed 's/base/wmlce/g')" && pip install seldon-core
ENV PATH=/opt/anaconda/envs/wmlce/bin:/opt/anaconda/condabin:/usr/local/nvidia/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
ENV CONDA_SHLVL=2
CMD [ "/bin/bash"]
