FROM ibmcom/powerai:1.6.0-all-ubuntu18.04-py3
COPY app /app
COPY nexright /nexright
WORKDIR /app
USER root
RUN mkdir /root/.ssh && mkdir -p /home/pwrai/.ssh
RUN mkdir -p /root/.jupyter && mkdir -p /home/pwrai/.jupyter && cp jupyter_notebook_config.py /root/.jupyter/ && cp jupyter_notebook_config.py /home/pwrai/.jupyter/
RUN chmod +x /app/ssh_key_copy.sh
RUN mkdir /run/sshd && mkdir /notebooks
COPY llvm-alternatives/llvm-alternatives /app
#RUN /opt/anaconda3/bin/conda install -c conda-forge jupyterlab
RUN apt-get update && apt-get install -y pkg-config git vim cmake gfortran wget libfreetype6-dev &&  wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add - && apt-get update && apt-get install -y libllvm-7-ocaml-dev libllvm7 llvm-7 llvm-7-dev llvm-7-doc llvm-7-examples llvm-7-runtime
ARG PATH=/opt/anaconda3/bin/:$PATH
ENV PATH=/opt/anaconda3/bin/:$PATH
ARG LICENSE=yes
ENV LICENSE=yes
SHELL ["/bin/bash", "-c"]
RUN cp /usr/bin/make /usr/bin/make.orig && echo "#!/bin/bash" >> /usr/bin/make && echo  "make -j 128 $1" >> /usr/bin/make && chmod +x /usr/bin/make 
RUN mkdir /sentencepiece/ && git clone https://github.com/google/sentencepiece.git /sentencepiece && cd /sentencepiece/ && mkdir build && \
cd build && cmake .. && make -j 68 && make install && ldconfig -v && cd ../python && python setup.py build && python setup.py install
#RUN mkdir /xgboost/ && git clone --recursive https://github.com/dmlc/xgboost /xgboost # && cd /sentencepiece/ && mkdir build && \
#cd build && cmake .. && make -j 68 && make install && ldconfig -v && cd ../python && python setup.py build && python setup.py install
#RUN echo "Status=9" > /opt/DL/license/lap_se/license/status.dat
RUN /opt/anaconda3/bin/conda install -y llvmlite pandas && \
 /opt/anaconda3/bin/pip install -r /nexright/requirements.txt 

#RUN git clone https://github.com/Qiskit/qiskit-aer.git && cd qiskit-aer/ && pip install scikit-build &&  pip install -U -r requirements-dev.txt && python ./setup.py bdist_wheel -- -j8 && cd dist && pip install qiskit_aer*.whl
RUN /opt/anaconda3/bin/pip install nodejs jupyterlab keras
#RUN /opt/anaconda3/bin/conda upgrade sympy --no-deps && pip install qiskit
RUN /opt/anaconda3/bin/conda install cmake
RUN /opt/anaconda3/bin/conda install cudatoolkit-dev
#RUN mkdir /xgboost/ && git clone --recursive https://github.com/dmlc/xgboost /xgboost && cd /xgboost/ && mkdir build && \
#cd build && /opt/anaconda3/bin/cmake .. -DUSE_CUDA=ON && make -j 68 && make install && cd ../python-package && python setup.py install
RUN apt-get update && apt-get install -y autoconf
ARG BLIS_ARCH=power9
ENV BLIS_ARCH=power9
RUN mkdir /cython-blis && git clone --recursive https://github.com/explosion/cython-blis.git /cython-blis && cd /cython-blis && pip install -r dev-requirements.txt && ./bin/generate-make-jsonl linux power9 && python setup.py build_ext --inplace && python setup.py bdist_wheel && python setup.py install
#git clone https://github.com/flame/blis.git /blis && cd /blis && ./configure power9 && make -j 64 && make install 
RUN pip install -e git+https://github.com/explosion/thinc_gpu_ops#egg=thinc_gpu_ops
RUN git clone https://github.com/explosion/cymem.git /cymem && cd /cymem && pip install -r requirements.txt && python setup.py build_ext --inplace && python setup.py bdist_wheel && pip install dist/*whl
RUN git clone https://github.com/adamjm/thinc /thinc && cd /thinc &&  pip install -r requirements.txt && python setup.py build_ext --inplace && python setup.py bdist_wheel && pip install dist/*whl
RUN git clone https://github.com/adamjm/spaCy /spacy && cd /spacy && mv include/numpy include/numpy.old && ln -s /opt/anaconda3/lib/python3.6/site-packages/numpy/core/include/numpy include/ && ls -ltr include/ && ls -ltr include/numpy/ && python setup.py build_ext --inplace && python setup.py bdist_wheel && pip install dist/*whl
RUN pip install fastai==1.0.51 tensorboardX==1.6 ffmpeg ffmpeg-python==0.1.17 youtube-dl>=2019.4.17
RUN cp /app/health-check-gpu /usr/bin/ && chmod +x /usr/bin/health-check-gpu
RUN pip install pyrouge tabulate six
CMD ["/bin/bash", "/app/ssh_key_copy.sh"]
